version: '2'

services:
  frontend:
    build: frontend
    volumes:
      - ./frontend:/usr/src/app/
      - /usr/src/app/node_modules
      - /usr/src/app/app/bower_components
    ports:
    - "3000:3000"

  db:
    image: mysql:5.7.13
    environment:
      MYSQL_ROOT_PASSWORD: '00000000'
      MYSQL_DATABASE: VIS
    ports:
      - "3306:3306"
    volumes:
      - ./db/db_dump:/docker-entrypoint-initdb.d

  web_backend:
    build: web_backend
    depends_on:
      - db
    ports:
      - "8080:8080"